# Created with WinGet Releaser using komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: LinwoodCloud.Butterfly.Nightly
PackageVersion: 2.3.0-beta.4
PackageLocale: en-US
Publisher: LinwoodCloud
PublisherUrl: https://www.linwood.dev/
PublisherSupportUrl: https://github.com/LinwoodDev/Butterfly/issues
PrivacyUrl: https://docs.butterfly.linwood.dev/privacypolicy
PackageName: Butterfly (Nightly)
PackageUrl: https://docs.butterfly.linwood.dev/
License: AGPL-3.0
LicenseUrl: https://github.com/LinwoodDev/Butterfly/blob/HEAD/LICENSE
ShortDescription: Butterfly is a note app where your ideas come first.
Moniker: butterfly-nightly
Tags:
- cross-platform
- note
- notes
- notes-app
- open-source
ReleaseNotes: |-
  - Add safe area around navigator
  - Add tooltips to the close icon button
  - Add swamp collaboration system in collaboration experiment
  - Add new material 3 slider
  - Add qr code for sharing collaboration link
  - Add barcode tool (#818)
  - Add ability to replace waypoints and customize origin (#817)
  - Rework settings cards (#822)
  - Rework input settings ui (#822)
  - Draw selection rect at the bounds of the canvas if it's outside the canvas
  - Use launch url as share link for collaboration
  - Rename xopp to Xournal++
  - Change ZIP export button label for clarity (#810)
  - Improve pattern background settings
  - Add search for term in caption in add dialog
  - Fix file list not refreshing when returning to home screen on desktop (#813)
  - Fix spacing in file preview on android (#814)
  - Fix temporary tool not being removed (#809)
  - Fix editable list tile subtitle not aligned with title
  - Fix svg images doesn't use the correct size
  - Fix opening a note from a recent files tile loads an outdated note and saves it (#816)
  - Fix filter chips in add dialog in comfortable ui
  - Fix editable list tile not having selected color
  - Fix setting the input mapping to a blank string would revert to the input's default setting after the app was restarted (#822)
  - Fix settings for "Pen only input" and "Input gestures" would be reverted after the app was restarted (#822)
  - Remove unsupported connections settings page on web
  Read more here: https://linwood.dev/butterfly/2.3.0-beta.4
ReleaseNotesUrl: https://github.com/LinwoodDev/Butterfly/releases/tag/v2.3.0-beta.4
ManifestType: defaultLocale
ManifestVersion: 1.9.0
